
//products
export const PRODUCT_LIST_START = 'PRODUCT_LIST_START';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE ='PRODUCT_LIST_FAILURE'

//single product
export const GET_PRODUCT_START = 'PRODUCT_START';
export const GET_PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

//cart 
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_ADD_ITEM_FAILURE = 'CART_ADD_ITEM_FAILURE'
export const CART_SAVE_SHIPPING_INFO = 'CART_SAVE_SHIPPING_INFO';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_EMPTY = 'CART_EMPTY'; //clear cart items

/* order */
//create
export const ORDER_CREATE_START = 'ORDER_CREATE_START';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';
//details
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
//pay
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';
//user orders
export const LIST_USER_ORDERS_REQUEST = 'LIST_USER_ORDERS_REQUEST';
export const LIST_USER_ORDERS_SUCCESS = 'LIST_USER_ORDERS_SUCCESS';
export const LIST_USER_ORDERS_FAIL = 'LIST_USER_ORDERS_FAIL';

//signin and signout
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SIGNOUT = 'SIGNOUT';

//signup
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//user details
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';


